// pages/index.js

import React, { useContext, useEffect, useState } from 'react';
import Head from 'next/head';
import { CartItemSContext } from '@/Context';
import Hero from "@/components/home/Hero";
import CardCarousel from "@/components/CardCarousel";

export default function Home() {
  const [products, setProducts] = useState([]);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchProducts();
  }, []);

  async function fetchProducts() {
    try {
      const res = await fetch(`/api/products?page=${1}&pageSize=10`);
      const data = await res.json();
      if (data.products && Array.isArray(data.products)) {
          setProducts(data.products);
      } else {
        throw new Error('Invalid data format received from API');
      }
    } catch (error) {
      console.error('Error fetching products:', error);
      setError(error.message);
    }
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div className="container mx-auto p-12 px-4 overflow-hidden max-w-[1300px]">
          <h2 className="text-3xl font-medium mb-10">Our Best Sellers</h2>
          {error ? (
            <p className="text-red-500">{error}</p>
          ) : (
            <CardCarousel products={products} />
          )}
        </div>
      </main>
    </>
  );
}